name: Doker Image CI

on:
   push:
      branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  forces:
    runs-on: ubuntu-latest
    container:
      image: fluidattacks/forces:latest
      env:
        tokenf : ${{ secrets.TOKENF }}
    steps:
      - name: Run Agent check
        run: forces --token ${tokenf} --strict --breaking 1 
